### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [bhensley/gtm-ninjatrack-integration-unofficial#2]
https://github.com/bhensley/gtm-ninjatrack-integration-unofficial/blob/db9b0382e39850ed6082202328c2a348db89a249/template.tpl#L54C83-L54C95

When reviewing your template, we've noticed that it is using user-defined parameters to build a URL. It's best practice to use [encodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [encodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by bhensley** [comment]
Thank you for the feedback, @semisight! I've gone ahead and updated the template to follow best practice here.
